# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
    
    # default loader to use for all filter sets
    data_loader: flysystem_loader

    filter_sets:
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:          [100, 100]
                    mode:          outbound
                    allow_upscale: true
        
        squared_thumbnail_x_small:
            filters:
                thumbnail:
                    size:          [50, 50]
                    mode:          outbound
                    allow_upscale: true
        
                    
